### PR TITLE
Use CARGO_INCREMENTAL instead of RUSTFLAGS for regex benchmarks.

### PR DESCRIPTION
**Pull request by michaelwoerister**
I think this is the more realistic test case.

cc @nikomatsakis 
r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I'm not opposed to doing this, though it will likely introduce a noticeable jump in data collected after this (and we can't really back-collect since CARGO_INCREMENTAL hasn't always existed).

r=me if we're fine with not back-collecting the data, otherwise we can discuss further.

cc @alexcrichton

**Comment by michaelwoerister** [comment]
Since CARGO_INCREMENTAL was introduced in January, back-collecting a few months should not be a problem, right?

**Comment by Mark-Simulacrum** [comment]
Wasn't aware it was introduced so far back. Mind converting the other benchmarks as well, or is there a particular reason only regex is being converted?

**Comment by nikomatsakis** [comment]
I don't have a strong opinion about this. It seems to me we probably ought to measure what users see.

**Comment by michaelwoerister** [comment]
The tokio tests are already based on CARGO_INCREMENTAL. The syntex case is a bit different, since the big crates come from crates.io and therefore would not be compile incrementally when using CARGO_INCREMENTAL.

**Comment by Mark-Simulacrum** [comment]
Alright, sounds good to me. I'll merge when I get a chance to delete data for back collection purposes.

**Pull request merged**
