### PR TITLE
Add `cranelift-codegen` benchmark.

### PR DESCRIPTION
**Pull request by nnethercote**
This commit imports Cranelift (revision
84567979ba18ad613d0066c0d8129393c9098a9c) into rustc-perf, and uses its
`cranelift-codegen` crate, which is by far its biggest crate, as the
benchmark.

The commit imports all of Cranelift even though only one of its crates
is benchmarked. This is consistent with how `style-servo` and
`script-servo` were done.

On my machine a "clean check" build takes 5.5s and a "clean opt" build
takes 16.7s, which is similar to some of the larger existing benchmarks,
though well short of the biggest three (`script-servo`, `style-servo`,
and `packed-simd`).

### CODE REVIEW

**Comment by nnethercote** [comment]
@sunfishcode: The `cranelift-codgen` struck me as the best crate within Cranelift to use as a benchmark for rustc compile speed. Does that sound good to you?

**Comment by Mark-Simulacrum** [comment]
This looks good to me (and CI passes); feel free to merge when @sunfishcode approves this. I'll try to deploy shortly thereafter.

**Comment by nnethercote** [comment]
@bnjbvr: Approval from you would be a fine alternative to approval from @sunfishcode.

**Comment by sunfishcode** [comment]
This sounds good to me, and yes, cranelift-codegen is a good crate to use here.

**Comment by nnethercote** [comment]
@sunfishcode: thank you for the confirmation.

@Mark-Simulacrum: I guess I have permissions to merge this. Which merge type should I use -- the default ("Create a merge commit")?

**Comment by Mark-Simulacrum** [comment]
Yep, that merge type works. I don't care too much about it.

**Pull request merged**
