### PR TITLE
Add wf-projection-stress-65510 benchmark.

### PR DESCRIPTION
**Pull request by eddyb**
This is a tweaked version of the stress test from https://github.com/rust-lang/rust/issues/65510.

The version in this PR should take about a couple seconds in `cargo check` (I was getting `2.24s` locally, using nightly) before any fix to https://github.com/rust-lang/rust/issues/65510 is attempted, and prevent regressions once a fix does land (as well as letting us measure a fix in the first place).

### CODE REVIEW

**Comment by nnethercote** [comment]
Thanks for updating the README file!

My only complaint is that the benchmark name is very long: 5 characters longer than `unicode_normalization`, which is currently the longest name. How about `wf-projection-stress` or `wf-stress-65510`?

**Comment by eddyb** [comment]
Oh, whoops, didn't consider that (I assume it's relevant to the UI?).
At the very least, `projection` could be `assoc` or `proj` easily.

@Mark-Simulacrum Can the little data already collected be renamed to avoid the longer name showing up anywhere at all?

**Comment by nnethercote** [comment]
We already have `issue-46449` and `regression-31157` benchmarks, too, so those are patterns that could be followed.

**Comment by Mark-Simulacrum** [comment]
Yes, whatever data we have can be renamed; it's a bit of work but not too bad. I'd appreciate a PR doing the rename itself though (moving the directories over and such), I can do the legwork of renaming older data myself right as I merge.

**Pull request merged**
