### PR TITLE
Bump SSL-related dependencies

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This removes the hyper and crates.io benchmarks. Both have become relatively old, and unfortunately due to dependencies to openssl-sys that makes them not well suited to continuing presence in tree. It then re-adds hyper at the current master (`hyper-2`) which introduces a crate that uses async/await quite a bit.

This also copies native-tls 0.2 and 0.1 in-tree, and patches out dependencies on them for sentry-cli and tokio-webpush-simple. Both native-tls versions are decoupled from openssl (entirely; the dependency edge is broken).

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
cc @nnethercote once we land this, I'm hopeful that you can start building these on your system (we spoke a month or two back about problems that we can now see on the new perf collector)

**Comment by nnethercote** [comment]
@Mark-Simulacrum Thanks! #466 is the issue I filed when I first encountered this.

You've chosen to just remove hyper and crates.io. Another possibility would be to update them to recent versions (and change their names, by appending a `-2` or a version number, to distinguish them from the old benchmarks). What do you think?

**Comment by Mark-Simulacrum** [comment]
Hm, so I thought about that briefly -- but the reality is that neither feels all that important; crates.io is compiled by almost no one, and to my knowledge is not a particularly "different" project to the others we have already (in terms of feature usage). Hyper is compiled quite a bit, but it also doesn't represent anything intrinsically unique in terms of feature usage I think.

Of the two, I think hyper has a much better reason to be re-added, given its prominence in the ecosystem, so I think I'll go ahead and do that, presuming it doesn't have any painful dependencies for us (I would like to avoid openssl or e.g. diesel dependencies that pull in a hefty build-time requirement where possible).

**Comment by nnethercote** [comment]
Fair enough! Thanks for making that change.

**Pull request merged**
