### PR TITLE
Add webrender-wrench benchmark

### LINKED ISSUE #311: create a benchmark for "wrench"
@gw3583 was telling me that the build times on webrender/wrench have gotten pretty bad. Maybe it would make a good benchmark.

Steps to reproduce:

- `git clone https://github.com/servo/webrender/`
- `cd webrender/wrench`
- `cargo build --release`

As of this writing, the current HEAD on webrender is [aa73c6a18](https://github.com/servo/webrender/commit/aa73c6a188d2885892b55903d126639f3d748c53).

### PR DESCRIPTION
**Pull request by michaelwoerister**
WebRender's `wrench` is a good test case because it has a linker invocation at the end and some large dependencies.

Closes #311.

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
This should also update collector/benchmarks/README.md I believe

**Comment by michaelwoerister** [comment]
Done. Good catch!

**Comment by Mark-Simulacrum** [comment]
Will merge once we get CI passing here (probably in around an hour).

**Comment by michaelwoerister** [comment]
:+1:

**Comment by Mark-Simulacrum** [comment]
Will deploy shortly.

**Comment by michaelwoerister** [comment]
The benchmark seems to fail with
```
could not execute "patch" "-Np1" "-i" "0002-change-in-dependency.patch".
```

I don't know what that is about. I'll remove the patch for now, I guess.

**Pull request merged**
