### PR TITLE
Add `profile_time_passes` subcommand.

### PR DESCRIPTION
**Pull request by nnethercote**
This subcommand profiles with -Ztime-passes.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I'm personally not opposed, but @nikomatsakis has told me in the past that time-passes shouldn't be used; instead we should use https://forge.rust-lang.org/profile-queries.html. Could you try that and see if it's more useful from your perspective?

**Comment by nnethercote** [comment]
I just tried the profile-queries stuff. I got empty output files, perhaps because my rustc build doesn't have debug assertions enabled.

One strange thing about the profile-queries is that you apparently have to run rustc twice, once with `-Z profile-queries -Z incremental=cache`, and then again with `-Z time-passes`, which doesn't fit into the existing collector code all that well.

**Comment by nnethercote** [comment]
I just tried again, using a rustc build in which debug assertions were enabled. Again, the output files are empty:
```
-rw-r--r-- 1 njn njn    0 May  7 16:41 profile_queries.ack
-rw-r--r-- 1 njn njn    0 May  7 16:41 profile_queries.counts.txt
-rw-r--r-- 1 njn njn 1333 May  7 16:41 profile_queries.html
-rw-r--r-- 1 njn njn    0 May  7 16:41 profile_queries.log.txt
```
(profile_queries.html has 1333 bytes of CSS and other stuff, but no actual data.)

@nikomatsakis: is the profile query stuff known to be broken?

**Comment by nnethercote** [comment]
@Mark-Simulacrum: @nmatsakis has confirmed (in #50780) that profile-queries is broken. Until a better thing comes along, I think this subcommand can be useful, and the implementation is very simple. Sound ok to land?

**Comment by Mark-Simulacrum** [comment]
Sounds good to me, thanks for confirming.

**Pull request merged**
