### PR TITLE
Add Cargo, Webrender, Ripgrep

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Incrementally adding a smaller portion of the benchmarks listed in #192 to see
if we can afford to do this on current hardware.

cc @michaelwoerister

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
We should also find some way long-term to do this without ~200,000 line additions, but that's a different problem we can solve later.

**Comment by nnethercote** [comment]
When I try to benchmark or profile `cargo` locally I get this error:
```
stderr=error: extra arguments to `rustc` can only be passed to one target, consider filtering
the package by passing e.g. `--lib` or `--bin NAME` to specify a single target
```
A normal `cargo build` in the `cargo` directory works, though.

**Comment by nnethercote** [comment]
I updated my rustc and the `cargo` benchmark is now working.

**Comment by nnethercote** [comment]
Looking at http://perf.rust-lang.org, ripgrep is showing up on both the graphs page and the compare page, but cargo and webrender are not.

**Pull request merged**
