### PR TITLE
De-ignore info integration test

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This *should* fail Travis.

Follow up of #112.

cc @alexcrichton, @nrc says that you are familiar with Travis, can you help us debug this failure? It doesn't fail locally.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Okay, this has failed Travis. Re-pasting diff:
```diff
--- rustc-perf/backend/tests/expected_results/info.json 2016-09-23 21:16:12.000000000 -0600
+++ travis-info.json    2016-09-23 21:53:11.000000000 -0600
@@ -12 +11,0 @@
-    "piston-image-0.10.3",
@@ -15,2 +13,0 @@
-    "rust-encoding-0.3.0",
-    "rust-encoding.0.2.32",
```

**Comment by alexcrichton** [comment]
Hm sorry I don't have a lot of context here, but some ideas off the top of my head:

* Does a fresh clone pass tests for you locally?
* Maybe a Cargo.lock isn't checked in and something's changing?
* Perhaps a dirty build directory?

**Comment by Mark-Simulacrum** [comment]
> Does a fresh clone pass tests for you locally?

Yes, and @dtolnay also verified that this passes locally.

> Maybe a Cargo.lock isn't checked in and something's changing?

Cargo.lock should not affect this, but either way, independent verification and my own testing within docker containers should make this impossible.

> Perhaps a dirty build directory?
Checked in docker (with no mounted volumes, just cloning), so unlikely.

**Comment by alexcrichton** [comment]
I was able to reproduce this locally with the latest nightly build on a fresh checkout, but it still doesn't reproduce locally for you?

**Comment by dtolnay** [comment]
I tried it again. In a fresh checkout of 339f1b5b1f433961589192f006abd587ed0e1507, the Travis build steps:

```sh
cd backend
cargo fmt -- --write-mode=diff
cargo build --verbose
cargo test --verbose
```

do not reproduce the failure for me.

**Comment by alexcrichton** [comment]
Sorry I may not be much help, I'm not sure I have enough context to help out here :(

**Comment by Mark-Simulacrum** [comment]
@alexcrichton Okay, I just reconfirmed, and I am also unable to reproduce the Travis failure locally, version information included below. Can you tell me what your environment is? I'm confused why Travis and you are seeing failures, but both @dtolnay and myself are not.

Also, I don't know if this even has potential to work, but post-clone:
```
cd backend
cargo clean
cargo fmt -- --write-mode=diff
cargo build
cargo test
cd ..
tar cjvf backend.tar.bz2 backend
md5sum backend.tar.bz2
=> d66ffa68b1ea8dd8ae635749a6002df0  backend.tar.bz2
```

Is this md5 equivalent for you as well?

```
rustc 1.14.0-nightly (289f3a4ca 2016-09-29)
binary: rustc
commit-hash: 289f3a4ca79916d6445b452fc19a18a1e42a879a
commit-date: 2016-09-29
host: x86_64-unknown-linux-gnu
release: 1.14.0-nightly
```

**Comment by alexcrichton** [comment]
[This container](https://gist.github.com/alexcrichton/7ac96e5b6b3233e2ddca89540c3b57cf) will reproduce the problem.

**Comment by dtolnay** [comment]
Nope, does not reproduce it for me. `docker build` downloads everything, clones the repo, builds, and the tests pass.

**Comment by Mark-Simulacrum** [comment]
@alexcrichton Unfortunately not; my results for that container are still that all tests pass. This is one odd bug!

**Comment by nrc** [comment]
Could this be platform-specific? I see that @Mark-Simulacrum is on Linux from one of the comments, I assume @alexcrichton is on OS X? Did Travis fail on all platforms?

**Comment by dtolnay** [comment]
I think Travis only ran (and failed) on Linux. I am using Linux and it passed.

The most confusing thing so far is how the same Dockerfile fails for Alex but passes for Mark and me. I am only involved to the extent that serde_json is involved so I have not looked at what the failing test is doing, but is it downloading data from somewhere? Is the server sending us different data? What else could cause it to behave differently in Docker? The Dockerfile is not copying in anything from the host.

**Comment by dtolnay** [comment]
I built the docker file on a mac laptop and it worked.

**Comment by Mark-Simulacrum** [comment]
re: @dtolnay 
> I have not looked at what the failing test is doing, but is it downloading data from somewhere? Is the server sending us different data? What else could cause it to behave differently in Docker?

Data is not being downloaded, the test fails because the server is sending us different data--but we spin up that server (it's the backend that we're testing). I don't see why it would behave differently within Docker.

> Could this be platform-specific?

It's possible, but as far as I know Travis is linux-based as well; we have only configured Travis to test on linux.

I have also built the docker container on a mac laptop (running sierra, in case it matters), all tests pass.

**Comment by Mark-Simulacrum** [comment]
After ~28 failed builds, this has now finally become green once more.

**Pull request merged**
