### PR TITLE
Add a benchmark for unicode_normalization

### PR DESCRIPTION
**Pull request by dotdash**
This crate uses huge matches, showing performance issues in areas not
yet covered by the existing benchmarks.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
This looks good to me. I'll wait for Travis to pass (it'll probably be a while as queue concurrency is currently still 3-5 for nursery due to migration to .com on Travis).

**Comment by dotdash** [comment]
Oh, sorry, I had created the lock file, but missed that it was listed in the accompanying .gitignore. It's in the commit this time.

**Comment by Mark-Simulacrum** [comment]
Will deploy later today!

**Comment by dotdash** [comment]
I didn't know that was a problem... :cry:

**Pull request merged**
